name: Node.js CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  NODE_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Create build directory
        run: |
          mkdir dist
          cp calculator.js dist/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-build
          path: dist/
          
      - name: Use secret
        env:
            DEMO_MESSAGE: ${{ secrets.DEMO_MESSAGE }}
        run: echo "Secret is configured"  